### ISSUE TITLE
Collab?

### ISSUE THREAD

**Issue by fasanar98** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#10]
Would it be possible to create a collab in order to try it?

**Comment by Janspiry** [comment]
Sorry, there is not enough time for me to do this in the short term.

**Comment by johnnyjmcivorv** [comment]
> Hi! I wrote a [colab notebook](https://colab.research.google.com/drive/1G1txPI1GKueKH0cSi_DgQFKwfyJOXlhY?usp=sharing) for upscaling 64x64 pixel images to 512x512.
> 
> Does this help?

for some reason i cannot find the output image in the results. it's under content right?

**Comment by MazeOfEncryption** [comment]
Should be under `/content/Image-Super-Resolution-via-Iterative-Refinement/experiments/<some folder>/results`

**Comment by johnnyjmcivorv** [comment]
> Should be under `/content/Image-Super-Resolution-via-Iterative-Refinement/experiments/<some folder>/results`

Yeah the results are blank

Didn't give me any errors though

**Comment by MazeOfEncryption** [comment]
> 
> 
> > Should be under `/content/Image-Super-Resolution-via-Iterative-Refinement/experiments/<some folder>/results`
> 
> Yeah the results are blank
> 
> Didn't give me any errors though

Hmm, that's weird. Could you share the output logs?
