### ISSUE TITLE
input 圖片為什麼需要很多時間才會輸出呢?(實測半小時以上)

### ISSUE THREAD

**Issue by huchi00057** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#101]
我使用infer.py去跑一張影像，但跑了半小時以上仍未結束。

還是因為我跑錯程式了?

**Comment by huchi00057** [comment]
我只是想看看放大後的像素品質

**Comment by Janspiry** [comment]
这个跟使用的GPU有一定关系，可以试下Google Lab的脚本。

**Comment by huchi00057** [comment]
OK, Thanks!!

**Comment by huchi00057** [comment]
Recently, i found the reason. Cause Colab use T4 GPU, and it ran slowly. However, i used NVIDAI 2070, it would lose lots of time.

**Comment by huchi00057** [comment]
Thanks again <3
