### ISSUE TITLE
about the checkpoint for regression baseline based on peak-PSNR

### ISSUE THREAD

**Issue by wangzhen699** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#108]
您好，非常感谢您的工作！1.请问您有遇到训练时checkpoint检查节点的值（PSNR）并不是稳定提高的情况？2.我想解决这个问题，您可以给我一些修改意见吗？非常感谢！

**Comment by Janspiry** [comment]
抱歉这么晚回复。有这种情况，这可能是模型的各种策略限制，比如学习率，模型结构，采样策略等。你可以参考最新的Diffusion工作去优化它，
