### ISSUE TITLE
how upscaling custom face?

### ISSUE THREAD

**Issue by molo32** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#11]
hello, i have a photo of a face, how upscaling face?

**Comment by Janspiry** [comment]
Hi，you can upscale the face by bicubic interpolation to specified size like code in `data_prepare.py`  first, then validate the pretrain model.

**Comment by molo32** [comment]
I do not understand, I have a blurred face, how do I make it hd?

**Comment by Janspiry** [comment]
Hi，you can find it in `Inference Alone` part.

**Comment by molo32** [comment]
help infer.py asks me for 3 images sr hr lr, but I only have one image.
the description says "HR (high resolution vanilla images), SR (images need to be processed)"
what is hr? Is it the same image in high resolution? It doesn't make sense if my goal is to go from low resolution to high resolution.

**Comment by Janspiry** [comment]
You can upscale the face by yourself to get the SR first. HR is the ground truth image, you can replace it with SR if you did not have ground truth image.
