### ISSUE TITLE
python infer.py -c [config file]

### ISSUE THREAD

**Issue by BlouseDong** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#112]
What is the config file here, and how should I set my weight file and image input during testing?

**Comment by QUEAHREN** [comment]
This config file is the same as the one you used for training, and you just need change the weight path specified by "resume_state" .

**Comment by Janspiry** [comment]
Thanks for the patient answer above. Feel free to reopen this issue if you have any questions.
