### ISSUE TITLE
Bug in the data augmentation code

### ISSUE THREAD

**Issue by Morefre** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#125]
Hi @Janspiry , 
In continue to my comment @ErezYosef  https://github.com/Janspiry/Image-Super-Resolution-via-Iterative-Refinement/issues/14#issuecomment-918394583
> I think its better to use the dedicated torchvision functions instead of implement them.

My Suggested implementation:
```python
    totensor = torchvision.transforms.ToTensor()
    hflip = torchvision.transforms.RandomHorizontalFlip()
    imgs = [totensor(img) for img in img_list]
    if split == 'train':
        imgs = torch.stack(imgs, 0)
        imgs = hflip(imgs)
        imgs = torch.unbind(imgs, dim=0)
    ret_img = [img * (min_max[1] - min_max[0]) + min_max[0] for img in imgs]
```

_Originally posted by @ErezYosef in https://github.com/Janspiry/Image-Super-Resolution-via-Iterative-Refinement/issues/14#issuecomment-918503497_
            
This code is incorrect because it randomly flips every image independently, as shown in the figures below:
![image](https://user-images.githubusercontent.com/101572174/247767830-eea605b1-b25f-4101-8561-8c2f37280ace.png)
![image](https://user-images.githubusercontent.com/101572174/247767989-6be68fd4-abf9-4611-8c56-ec4b58e32f0d.png)

**Comment by javierhndev** [comment]
I don't think that is a bug (unless you don't want to flip the images of your own project). For every epoch, some of the images will be horizontally flipped. That artificially increases the amount of images that the model is trained on.
