### ISSUE TITLE
DDPM Model Sample.py did not converge due to n_timestep

### ISSUE THREAD

**Issue by ErezYosef** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#13]
Hello.
I trained the default model and the ddpm model didn't converge for me after 550,000 iters.
the results always was something like that:
![550000_4_sr](https://user-images.githubusercontent.com/57535452/132990523-053689ac-74cf-4b75-8694-84a9ba217140.png)

I changed in line 68 to: `n_timestep=2000`
https://github.com/Janspiry/Image-Super-Resolution-via-Iterative-Refinement/blob/0f31547f3d0429dcae23cf528059b7a69e0e7fca/config/sample_ddpm_128.json#L59-L71

Now the model converges good.
Is it supposed to be always equal in train and val phases?

Thanks.
Erez.

**Comment by Janspiry** [comment]
That's a great problem. val.n_timestep determines the quality of sampling, which is independent with training process. If you use more iterations (validation n_timestep) in sampling, you can get  more reasonable visual results. Actually, we try to use 100 timesteps to sample, then get similiar results like yours, which is improved on the `SR3` model.

**Comment by ErezYosef** [comment]
Thanks,
Actually, you are right. The val setup shouldn't change the train process. (I missed this point).
But the limits `linear_start` `linear_end` should stay the same as in train? (even though I use different `n_timestep`  )

**Comment by Janspiry** [comment]
Yes, we should just adjust the interval of beta schedule to increase iterations. A funny thing is that if we **use SR as the initial sample image rather than random noise**, we can change the range of beta schedule to use less timesteps, which also can achieve a good result.

**Comment by ErezYosef** [comment]
Thanks! 👍
