### ISSUE TITLE
Bug in Image Augmentations

### ISSUE THREAD

**Issue by ErezYosef** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#14]
Hi,
When reading and augment the data we call:
https://github.com/Janspiry/Image-Super-Resolution-via-Iterative-Refinement/blob/0f31547f3d0429dcae23cf528059b7a69e0e7fca/data/util.py#L64-L71

The bugs:
1. This line iterate over the first dimension of the numpy image (because the function `augment(img, split)` called with single image)
https://github.com/Janspiry/Image-Super-Resolution-via-Iterative-Refinement/blob/0f31547f3d0429dcae23cf528059b7a69e0e7fca/data/util.py#L41

2. the `hflip` get the `split` value. ( We should call it `augment(img, split=split)` )
https://github.com/Janspiry/Image-Super-Resolution-via-Iterative-Refinement/blob/0f31547f3d0429dcae23cf528059b7a69e0e7fca/data/util.py#L26

Suggested solution:
```python
def transform_augment(img_list, split='val', min_max=(0, 1)):
    imgs = [transform2numpy(img) for img in img_list]
    imgs = augment(imgs, split=split)
    ret_img = [transform2tensor(img, min_max) for img in imgs]
    return ret_img
```

Please let me know if it's correct.

**Comment by Janspiry** [comment]
You are right! The augment of single image will affect the network performance.Thanks for your advice, I will update it soon.

**Comment by ErezYosef** [comment]
The augmentations are disabled since the default value `split='val'` remains in `augment` function...
Of course, with the augmentations, it supposes to perform better.
I think its better to use the dedicated torchvision functions instead of implement them, as follows:
```python
    totensor = torchvision.transforms.ToTensor()
    hflip = torchvision.transforms.RandomHorizontalFlip()

    imgs = [totensor(img) for img in img_list]
    if split == 'train':
        imgs = torch.stack(imgs, 0)
        imgs = hflip(imgs)
        imgs = torch.unbind(imgs, dim=0)
    ret_img = [img * (min_max[1] - min_max[0]) + min_max[0] for img in imgs]
```

**Comment by ErezYosef** [comment]
Hi @Janspiry , 
In continue to my comment @ErezYosef  https://github.com/Janspiry/Image-Super-Resolution-via-Iterative-Refinement/issues/14#issuecomment-918394583
> I think its better to use the dedicated torchvision functions instead of implement them.


My Suggested implementation:
```python
    totensor = torchvision.transforms.ToTensor()
    hflip = torchvision.transforms.RandomHorizontalFlip()
    imgs = [totensor(img) for img in img_list]
    if split == 'train':
        imgs = torch.stack(imgs, 0)
        imgs = hflip(imgs)
        imgs = torch.unbind(imgs, dim=0)
    ret_img = [img * (min_max[1] - min_max[0]) + min_max[0] for img in imgs]
```

**Comment by Janspiry** [comment]
Thanks for your valuable suggestions. I used `torchvision` in earlier versions rather than `numpy`, which does lead to a decrease in processing speed. I will update it in the newest code.

**Comment by Janspiry** [comment]
Oh, I think you are right. You can use `torch.flip` to fix it.

**Comment by qiufengchuiwoyisan** [comment]
> 

I meet the same problem.
I use pytorch=1.2. This may be a version problem.
I delete this flip process，and the program ran successfully.

**Comment by kada0720** [comment]
@Janspiry @ErezYosef 
hi, thank you for the code.
If my HR and SR sizes are different, how should I modify the code? When I use torch.stack, the image size should be the same.

Looking forward to receiving your answer, thank you very much~
