### ISSUE TITLE
prepare_data TypeError: cannot pickle 'Environment' object 

### ISSUE THREAD

**Issue by Satournine** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#141]
\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'Environment' object

\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by raminduw200** [comment]
Change the --n_worker to 0 (default is 3)
Reference: https://github.com/pytorch/examples/issues/526
