### ISSUE TITLE
Will it work on text images?

### ISSUE THREAD

**Issue by YC7225** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#17]
i was  thinking if apply this on low quality text images will it improve the quality using existing weights?

**Comment by Janspiry** [comment]
You can use it as the pre-trained model  and finetune on quality text images dataset.

**Comment by YC7225** [comment]
But how can I test this on single image..

**Comment by Janspiry** [comment]
Hi，you can find it in Inference Alone part.

**Comment by YC7225** [comment]
Let me know in config where I need to provide a image path?

**Comment by Janspiry** [comment]
![image](https://user-images.githubusercontent.com/32922494/134526307-8a65867e-7d57-406e-a115-c91e377c111f.png)

**Comment by YC7225** [comment]
i will try and let you know thanks!
