### ISSUE TITLE
Python and Torch version

### ISSUE THREAD

**Issue by truongtx8** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#18]
I have an issue when loading the dataset with file `data/LRHR_dataset.py`
`self.data_len = min(self.data_len, self.dataset_len)
TypeError: '<' not supported between instances of 'int' and 'NoneType'`

Could you please share the python and torch versions?

Thanks in advance.

**Comment by Janspiry** [comment]
`Python: 3.7, Pytorch: 1.7.1`
But I think you need to confirm whether self.data_len or self.dataset_len is undefined.
