### ISSUE TITLE
Training on another big datasets

### ISSUE THREAD

**Issue by attashe** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#19]
Have you plans training this network on ImageNet, COCO, or another datasets? Can model demonstrate good results in common objects photo (nature, city) after that?

**Comment by Janspiry** [comment]
I am sorry not to train this model with a natural image dataset like COCO. According to the paper results and our faces datasets experiments, it should also have a not bad performance.

**Comment by attashe** [comment]
I'm trying learn on COCO in next week

**Comment by Janspiry** [comment]
Waiting for your good news.

**Comment by attashe** [comment]
![lr](https://user-images.githubusercontent.com/8243605/137566935-a0ba372e-47bb-4624-b23d-4b98f37704e1.png)
![sr](https://user-images.githubusercontent.com/8243605/137566942-c4110e28-a43a-435c-ad60-e5a232dc7508.png)

32x32 -> 256x256, dataset was prepared from COCO with sliding window, PSNR ~21, inference on 256x256 crops and merge it back
