### ISSUE TITLE
Inference: PIL.UnidentifiedImageError: cannot identify image file

### ISSUE THREAD

**Issue by mansum6** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#2]
I trained and when running inference using following command:

python sr.py -p val -c config/myver.json

i get following error:

PIL.UnidentifiedImageError: cannot identify image file

File "/content/ISR/data/LRHR_dataset.py", line 59, in __getitem__
    img_LR = Image.open(BytesIO(lr_img_bytes)).convert("RGB")
  File "/usr/local/lib/python3.7/dist-packages/PIL/Image.py", line 2896, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7fab1d486890>

**Comment by Janspiry** [comment]
Thanks for your attention. 
I think this is a dataset path error. Make sure you prepare the corresponding data in default lmdb format, and set the correct validation dataroot ("data/Celeba in my config["dataset"]["val"]) if you select `val` phase.

**Comment by Janspiry** [comment]
Hello, I found another possibility may caused this Error: indexes of your source image data are **not continuous**, which lead to `getitem` load None by sequential reading. I fixed the bug in newest version.
