### ISSUE TITLE
Can you give me an example?

### ISSUE THREAD

**Issue by feng1990liu** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#24]
Can you give me an example ， like I have a low resolution images picture ,how i run  out a super resolution images?
python sr.py -p val -c config/sr_sr3_64_512.json and  python eval.py not work

**Comment by MazeOfEncryption** [comment]
@Janspiry The colab script has been added to the README, I think you can mark this issue as resolved now.

**Comment by DisaKzionda** [comment]
> @Janspiry The colab script has been added to the README, I think you can mark this issue as resolved now.

![image](https://user-images.githubusercontent.com/53359732/141675783-566eebcc-84bd-420c-9481-0a8828955a0b.png)
