### ISSUE TITLE
cuda out of memory

### ISSUE THREAD

**Issue by dmjeong** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#25]
now i'm in tutorial. i downloaded FFHQ 512×512 dataset and i converted it 64_512 dataset to use prepare_data.py.

and then generate following code that python sr.py -p train -c config/sr_sr3_64_512.json

but i got this error code that cuda out of memory.

what kind of parameter do i have to fix for clear this error code?

![image](https://user-images.githubusercontent.com/29299631/140670616-43b0b561-076a-4c84-b3ff-7c34a9f178f0.png)

**Comment by Janspiry** [comment]
![image](https://user-images.githubusercontent.com/32922494/140731647-42d5ea20-93c5-41f0-bcea-8d17f1c457ff.png)
Change the batch size or model parameters.
