### ISSUE TITLE
Mobile version possible&practical?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#27]
Hello,

I just watched a video demonstrating this :
https://youtu.be/WCAF3PNEc_c

It seems like an amazing&incredible work!

Would it be possible to offer this as a library for mobile, such as Android? Could be great to import it to use on Java/Kotlin based apps...

Or it's already possible?

I requested it in the past:
https://issuetracker.google.com/issues/198311063

Also, I don't see the license information. OK to use for any purpose?

**Comment by Janspiry** [comment]
Thanks for your attention. 
I have no experience in developing library, so I'm  not sure it is appropriate considering its parameters. 
And this is just an unofficial implementation, you can use this code freely.

**Comment by AndroidDeveloperLB** [comment]
@Janspiry 
1. Do you think it's CPU/GPU/RAM intensive task? 
2. Would it be a practical thing to run on mobile phones? Or it might crash (out of memory) or take a huge amount of time there?
3. What are the RAM requirements of it? Probably based on the input image, no?
4. How much space would it take to have this library inside the app?

**Comment by Janspiry** [comment]
It requires adequate GPU memory and I think it is hard to run on mobile phones. You can use the pretrained model to get specific values. And so sorry I have no experience in developing library, it is uncertain whether the model can be simplify.

**Comment by AndroidDeveloperLB** [comment]
@Janspiry Can you please perform some benchmarks that could give a clue about it being possible to run nicely on mobile phones?
Suppose you try to take what you think is the hardest thing (out of all the tests you've got here), check how much RAM it used and in how much time.

**Comment by Janspiry** [comment]
For example, it need to spend about 3 minutes to get 512*512 image and cost  >1000 MB memory on GPU.

**Comment by AndroidDeveloperLB** [comment]
@Janspiry Interesting. 
You probably mean the " 64×64 -> 512×512" test I see on the repository's main page.
What is your time&RAM estimation for a "132x132  -> 512x512 " test, for example?
