### ISSUE TITLE
Memory leak in multiprocessing pool

### ISSUE THREAD

**Issue by drew6017** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#28]
(windows10 / python3.6 / conda:latest / all-other-packages:latest)

There is a memory leak somewhere in the multiprocessing section:
https://github.com/Janspiry/Image-Super-Resolution-via-Iterative-Refinement/blob/de9d0b1bb7f4a85d958fb2800c4f56881b279697/data/prepare_data.py#L65

Running 8 workers on a system with 16GB of ram will lead to a crash within ~1-2mins and a nasty pagefile increase to 40GB! I re-wrote the script using the older Process() api and no shared variables between instances which fixed the issue so its probably something to do with data passing.

All of my tests were done on the full `celebahq` dataset.

**Comment by Janspiry** [comment]
Thanks for you advice. I will try it soon.

**Comment by Janspiry** [comment]
And can you offer your code? Thanks.

**Comment by drew6017** [comment]
https://gist.github.com/drew6017/2167e7adba10a152d776ae514388ea03

**Comment by drew6017** [comment]
I added in a shared var for the total count for that gist to make it a little easier to see the progress.

**Comment by Janspiry** [comment]
Thanks for your  succinct code, I try it successfully. Could you contribute it to the repo, or Could I update to the data_prepare.py?
