### ISSUE TITLE
No difference

### ISSUE THREAD

**Issue by hjrobins** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#29]
I have tried using my own images, but I have not got any difference between hr (which is just upscaled lr) and inf.
My photos are black and white though, I don't know if that would have any effect on it. I seems to me, this is only copying whatever is in the hr folder. Because it doesn't matter if I use actual ground truths or upscaled low res images, the inference looks the same as it.

**Comment by Janspiry** [comment]
Hi，INF is just upscaled from lr and HR is the vanilla high resolution images. You should upscale from INF and compare with HR. What did you mean  have not got any difference?
And the model is trained in face datasets, maybe you should retrain it in your images for better results.

**Comment by hjrobins** [comment]
Oh okay, sorry. So, I only have low resolution input images, which are faces, and I was hoping I would be able to use the pretrained model to make it higher resolution, however the output is very noisy. I'm using your pretrained model I830000_E32. It does it even with the celebrity dataset.

I've tried training it as well, but stopped it after only 30000 iterations, and then when I've tried to resume it, by putting the 30000 model into the config file path, it starts from the beginning again, so I think it's ignoring the model. Unless I need to change anything else to resume state?

**Comment by Janspiry** [comment]
Yes, you can refer to `Inference Alone` part if you didn't have high resolution input images. 
And I think it should work after your operation, can you offer more information like file path and config file?

**Comment by hjrobins** [comment]
Okay, so I'll modify sr_sr3_64_512.json, to have the resume_state lead to "I830000_E32". I'll have those .pth files in the main directory. And I'll have my 24 photos in celebahq_64_512, they have been through the prepare script. I run "python infer.py -c config/sr_sr3_64_512.json", and after 5 minutes, this is my output.  
![0_1_sr_process](https://user-images.githubusercontent.com/52089587/141611217-760be6d3-fa64-4855-b845-c439c1435d10.png)

**Comment by Janspiry** [comment]
The results is bad, so it will be better to retrain it. Have it a visual output in your 30000 iterations retrain process?

**Comment by hjrobins** [comment]
Okay, so I do still think it is ignoring any models I give it. I stopped the training at I190000_E4. And then I changed the config file to point to that pth file. And I ran the train script again and it's started from 0 again. Is there anything else I need to change to the config file to let it resume state, or just use the model I tell it to use?

**Comment by hjrobins** [comment]
Is it `"resume_state": null` that needs changing as well?

**Comment by hjrobins** [comment]
Ah finally got it working. So it needs to be.
`"resume_state": "I830000_E32"
	   //"resume_state": "I830000_E32"`

**Comment by AndreyStille** [comment]
> Ah finally got it working. So it needs to be. `"resume_state": "I830000_E32" //"resume_state": "I830000_E32"`

Hi
HAve you finally reached good results?
