### ISSUE TITLE
Training epoch

### ISSUE THREAD

**Issue by Xuyang-FD** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#3]
I'm a little confused about training logic。Is the code below only used to control training one epoch?
```   python
# line 65-71 of sr.py
if opt['phase'] == 'train':
        while current_step < n_iter:
            current_epoch += 1
            for _, train_data in enumerate(train_loader):
                current_step += 1
                if current_step > n_iter:
                    break
```

**Comment by Janspiry** [comment]
Thanks for your attention.
The training just end with limit iteration that corresponding with dataloader batch size, and epoch only records how many times the dataset has been trained.

**Comment by Xuyang-FD** [comment]
Got it!
Thanks for your reply~
