### ISSUE TITLE
release of another pretrained model for imagenet

### ISSUE THREAD

**Issue by Vaillus** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#31]
Thank you for the release of the pretrained model for faces.
For my particular use case, a model pretrained on imagenet could be more useful and I can't manage to train it on my dataset (apparently, 256 GB GPU is required even when I set the parameters to lower values, and I only have a 8GB GPU)
Could you also release the model pretrained on imagenet?

Thank you for your work.

**Comment by Janspiry** [comment]
Thanks for your attention, and I'm so sorry for this. I also haven't adequate GPU resource for more widely experiments. Otherwise, I will have further follow-up on the 64×64 to 512×512 or 1024 ×1024 task.

**Comment by coderSHeE** [comment]
hy what can i do?
