### ISSUE TITLE
UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.

### ISSUE THREAD

**Issue by saadbruno** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#36]
So, when running the command:
`python data/prepare_data.py --path /content/Image-Super-Resolution-via-Iterative-Refinement/input/ --size 64,512 --out ./dataset/celebahq`

I get the following output:

```
0/1 images processed
/usr/local/lib/python3.7/dist-packages/torchvision/transforms/functional.py:405: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  "Argument interpolation should be of type InterpolationMode instead of int. "
0/1 images processed
```

I tried manually changing all instances of  `Image.BICUBIC` with `InterpolationMode.BICUBIC` and it didn't work. In this case I got `0/1 images processed` and that was it.

Also tried running both in the Google Collab project, and also locally an Ubuntu, and got the same problem both times.

Any directions on what i could do to fix it? Thanks a lot!

**Comment by johnswan** [comment]
I just made a PR to fix this

**Comment by Janspiry** [comment]
Yeh, it works on higher torch version.

**Comment by johnswan** [comment]
Worth merging my PR?

**Comment by Janspiry** [comment]
Hey, I just did a PR, and it was not works?
