### ISSUE TITLE
Iteration Count

### ISSUE THREAD

**Issue by MyUsernamee** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#39]
This may be a dumb question, but is there a way to change the amount of "diffusion steps" or iterations the model does when upscaling. Right now I think it is 2000. Thank you so much in advance! :+1: Amazing project might I add!

**Comment by Janspiry** [comment]
![image](https://user-images.githubusercontent.com/32922494/147814190-41cec3ac-d478-4bc3-8928-1a0045fe1d72.png)
You can change the n_timestep in val by yourself.

**Comment by MyUsernamee** [comment]
Thank you!
