### ISSUE TITLE
ZeroDivisionError

### ISSUE THREAD

**Issue by RiteshpratapS** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#4]
error while running sr3.py file

export CUDA_VISIBLE_DEVICES=0
21-08-16 15:31:59.624 - INFO:   name: basic_sr_ffhq
  phase: val
  gpu_ids: [0]
  path:[
    log: experiments\basic_sr_ffhq_210816_153159\logs
    tb_logger: experiments\basic_sr_ffhq_210816_153159\tb_logger
    results: experiments\basic_sr_ffhq_210816_153159\results
    checkpoint: experiments\basic_sr_ffhq_210816_153159\checkpoint
    resume_state: model/pretrained/checkpoint/I640000_E37_gen.pth
    experiments_root: experiments\basic_sr_ffhq_210816_153159
  ]
  datasets:[
    train:[
      name: FFHQ
      mode: HR
      dataroot: dataset/ffhq
      l_resolution: 16
      r_resolution: 128
      batch_size: 4
      num_workers: 8
      use_shuffle: True
      data_len: -1
    ]
    val:[
      name: CelebaHQ
      mode: LRHR
      dataroot: dataset/celebahq
      l_resolution: 16
      r_resolution: 128
      data_len: 50
    ]
  ]
  model:[
    which_model_G: sr3
    finetune_norm: False
    unet:[
      in_channel: 6
      out_channel: 3
      inner_channel: 64
      channel_multiplier: [1, 2, 4, 8, 8]
      attn_res: [16]
      res_blocks: 2
      dropout: 0.2
    ]
    beta_schedule:[
      train:[
        schedule: linear
        n_timestep: 2000
        linear_start: 1e-06
        linear_end: 0.01
      ]
      val:[
        schedule: linear
        n_timestep: 2000
        linear_start: 1e-06
        linear_end: 0.01
      ]
    ]
    diffusion:[
      image_size: 128
      channels: 3
      conditional: True
    ]
  ]
  train:[
    n_iter: 1000000
    val_freq: 10000.0
    save_checkpoint_freq: 10000.0
    print_freq: 200
    optimizer:[
      type: adam
      lr: 0.0001
    ]
    ema_scheduler:[
      step_start_ema: 5000
      update_ema_every: 1
      ema_decay: 0.9999
    ]
  ]
  distributed: False

Traceback (most recent call last):
  File "sr.py", line 45, in <module>
    val_set = Data.create_dataset(dataset_opt, phase)
  File "D:\rp\Projects\SuperResolution\sr3\data\__init__.py", line 33, in create_dataset
    need_LR=(mode == 'LRHR')
  File "D:\rp\Projects\SuperResolution\sr3\data\LRHR_dataset.py", line 14, in __init__
    readahead=False, meminit=False)
lmdb.Error: dataset/celebahq: The system cannot find the path specified.

(facerec) D:\rp\Projects\SuperResolution\sr3>python eval.py -p boot_img
Traceback (most recent call last):
  File "eval.py", line 36, in <module>
    avg_psnr = avg_psnr / idx
ZeroDivisionError: float division by zero

**Comment by Janspiry** [comment]
Hi, eval.py just evaluate generated image pairs. I think you should prepare images in lmdb format or change the LRHR_dataset.py to support PNG format, then use `python sr.py -p val`  to generate images.
