### ISSUE TITLE
There is no prepare.py file

### ISSUE THREAD

**Issue by ayulockin** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#42]
As stated by the Issue title, there is no `prepare.py` file in the repository. I think it should be `prepare_data.py` instead.

In the markdown shown below, it should be: `python data/prepare_data.py ..`
<img width="839" alt="image" src="https://user-images.githubusercontent.com/31141479/148766045-022cd76e-31b7-48ba-9ed1-785feef31444.png">

**Comment by Janspiry** [comment]
Thanks, I fixed it.
