### ISSUE TITLE
Is it sr_16_128 folder to put 16x16 resolution images with bicubic interpolation?

### ISSUE THREAD

**Issue by RichardJie** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#43]

**Comment by yee-ran** [comment]
@Janspiry Hey, so I'm confused now after reading this [issues40](https://github.com/Janspiry/Image-Super-Resolution-via-Iterative-Refinement/issues/40). Take this as an example, so lr_16 folder contains 16*16 downsample images with bicubic interpolation, hr_128 folder contains high resolution 128*128 images, sr_16_128 contains 128*128 images that are upsampled from 16*16 images with bicubic interpolation?

**Comment by Janspiry** [comment]
@yee-ran The process is right and I give some example in the repo. I apologize for misreading the above question, I will fix it.
