### ISSUE TITLE
ImportError: cannot import name 'InterpolationMode' from 'torchvision.transforms'

### ISSUE THREAD

**Issue by galenoshea** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#45]
tried running data/prepare_data.py on Ubuntu and received the following error.

Traceback (most recent call last):
  File "data/prepare_data.py", line 10, in <module>
    from torchvision.transforms import InterpolationMode
ImportError: cannot import name 'InterpolationMode' from 'torchvision.transforms'

**Comment by Janspiry** [comment]
Sorry, it was a pytorch version problem, I fixed it in lastest version.
