### ISSUE TITLE
am i the only one having this problem???

### ISSUE THREAD

**Issue by Annnnmmmm** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#46]
from model.base import BaseModule
from model.nn import WaveGradNN

is wrong*-*

**Comment by Janspiry** [comment]
I'm sorry for this, you can skip this file since `WaveGrad` module is not used in training and we just copy its partial codes to `diffusion` steps.  Maybe you can delete it?

**Comment by Annnnmmmm** [comment]
thank you very much
