### ISSUE TITLE
Failed to create env

### ISSUE THREAD

**Issue by HydrofinLoewenherz** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#49]
Hello, I'm currently having a problem while running the setup. I'm also quite inexperienced in Conda and Python. What am I doing wrong here?

```
$ conda env create -f core/environment.yml
Collecting package metadata (repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/linux-64/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
'https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/linux-64'
```

**Specs:**
- WSL 2: `5.10.60.1-microsoft-standard-WSL2` with `Ubuntu`
- using Anaconda: `conda 4.11.0`
- on `Windows 10`
- GPU (8 GiB): `NVIDIA GeForce RTX 2060 SUPER`

**Comment by Janspiry** [comment]
Sotty for this, You can try another plan or install it follow the dependencies files.
