### ISSUE TITLE
Multi-gpu support

### ISSUE THREAD

**Issue by Xuyang-FD** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#5]
Multi-gpu training support seems to be problematic~
When the loss type is "l1", `l_pix` in line47 of `model/model.py` will be a list. Thus, `l_pix.backward()` will not run correctly.
When  the loss type is "l1",  line47 of `model/model.py`  should be `l_pix = self.netG(self.data).mean()`？
I'm not sure if the change is correct.

**Comment by Janspiry** [comment]
Thanks for your feedback.
I will try your advice and fix the code as soon as possible since there is only one GPU on my machine now.

**Comment by Janspiry** [comment]
Hello, I use the code ` loss_func =nn.L1Loss(reduction='sum').to(device) , l_pix = l_pix.sum()/int(b*c*h*w)`  considering different batch sizes in multi-gpu. Let me know if you have any further questions.
