### ISSUE TITLE
Not getting great results

### ISSUE THREAD

**Issue by ayulockin** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#50]
Hey @Janspiry, I was trying to infer on a few images to get their super-resolution variants. 

Here's the result of the inference: https://wandb.ai/ayush-thakur/sr_ffhq/runs/9zfkm2zm

![image](https://user-images.githubusercontent.com/31141479/150032414-50e2d044-64cc-481e-9325-7d8ea33b7154.png)

I have used the following checkpoint: 16×16 -> 128×128 on FFHQ-CelebaHQ

The output images (middle column) are definitely super-resolution but not preserving the semantics very well. Can you let me know what I might be missing?

**Comment by Janspiry** [comment]
Maybe you need to retrain it on a new dataset because there are quite different data distribution.
