### ISSUE TITLE
attn_res and finetune_norm parameters

### ISSUE THREAD

**Issue by AndreyStille** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#52]
Hi
What is finetune_norm and attn_res parameters in the config? Why first is false and second is commented?

**Comment by Janspiry** [comment]
![image](https://user-images.githubusercontent.com/32922494/154026203-96d26d28-d09e-400f-b1f1-8d58fd3a1499.png)
As show above, finetune_norm will just optimize partial network, it depends on you. 
attn_res indicates size of attention map  in U-Net.

**Comment by AndreyStille** [comment]
Thanks a lot!
