### ISSUE TITLE
colab errors

### ISSUE THREAD

**Issue by AscendChina** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#53]
/content/Image-Super-Resolution-via-Iterative-Refinement
0/2 images processed/usr/local/lib/python3.7/dist-packages/torchvision/transforms/functional.py:405: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  "Argument interpolation should be of type InterpolationMode instead of int. "
/usr/local/lib/python3.7/dist-packages/torchvision/transforms/functional.py:405: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  "Argument interpolation should be of type InterpolationMode instead of int. "
0/2 images processed 

Traceback (most recent call last):
  File "infer.py", line 12, in <module>
    import wandb
ModuleNotFoundError: No module named 'wandb'

**Comment by Janspiry** [comment]
![image](https://user-images.githubusercontent.com/32922494/155263805-0150285c-6568-4b44-9219-c927569c0b43.png)
So sorry for this, and you can install wandb temporarily, I will fix it soon.
