### ISSUE TITLE
Question about posterior variance

### ISSUE THREAD

**Issue by rodrigovimieiro** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#54]
Hi, thank you for sharing all the codes!

I have a question about the implementation and the equations of the paper. 

In the testing phase, using the SR3 model and the conditional input:

- What is the reference for this [posterior variance](https://github.com/Janspiry/Image-Super-Resolution-via-Iterative-Refinement/blob/master/model/sr3_modules/diffusion.py#L128)? In the paper, they used `sqrt(1 - \alpha_t)`. In the same equation, why divide by 2 and take the exponential in this [line](https://github.com/Janspiry/Image-Super-Resolution-via-Iterative-Refinement/blob/master/model/sr3_modules/diffusion.py#L174)? 

Thanks!

**Comment by Janspiry** [comment]
1. In the vanilla paper "Denoising Diffusion Probabilistic Models" says:
![image](https://user-images.githubusercontent.com/32922494/157155429-544db217-3e63-4e74-a70f-5c60ab11e83a.png), `\beta_t = 1 - \alpha_t` in this. `sqrt(1 - \alpha_t)` is the first method, and we just choose the second to get the  posterior variance. Thanks for this and I will add this to README.md.
2. we calculate the [q_posterior^2](https://github.com/Janspiry/Image-Super-Resolution-via-Iterative-Refinement/blob/8a75df33d9ed1a2cc0da22f36f576abfc9482913/model/sr3_modules/diffusion.py#L148) using the [its' log](https://github.com/Janspiry/Image-Super-Resolution-via-Iterative-Refinement/blob/8a75df33d9ed1a2cc0da22f36f576abfc9482913/model/sr3_modules/diffusion.py#L134), so we need to divide by 2 and take the exponential to get the `sqrt(posterior variance) = sqrt(\beta_t`).

**Comment by rodrigovimieiro** [comment]
That make sense! Thank you for the explanation!
