### ISSUE TITLE
extensiton to more image-to-image translation

### ISSUE THREAD

**Issue by JunMa11** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#55]
Hi @Janspiry ,

Thanks for the great repo. Really nice work.

I was wondering is there any plan to extend this repo to more image-to-image tasks? 
For example https://iterative-refinement.github.io/palette/

**Comment by Janspiry** [comment]
Hi, thanks for your attention.
I might try it in April/May, if I have enough time.
