### ISSUE TITLE
Suggestions on how to apply this technique to non-image tasks

### ISSUE THREAD

**Issue by sgbaird** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#56]
I come from a materials science background, and am interested in applying this technique to a non-image task. Do you know of any applications of this method that don't involve images?

**Comment by Janspiry** [comment]
Yeh，you can see some applications in NLP like：[WaveGrad: Estimating Gradients for Waveform Generation](https://arxiv.org/abs/2009.00713).
More examples should can be found in papers who cite [Denoising Diffusion Probabilistic Models](https://arxiv.org/pdf/2006.11239.pdf).
