### ISSUE TITLE
"CUDA out of memory error" while training

### ISSUE THREAD

**Issue by ashinberish** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#57]
RuntimeError: CUDA out of memory. Tried to allocate 48.00 MiB (GPU 0; 6.00 GiB total capacity; 4.05 GiB already allocated; 0 bytes free; 4.17 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by ashinberish** [comment]
My batch size is 2

**Comment by Janspiry** [comment]
It will use more than 10GB memory if you run the 64->512 super-resolution task, so you should adjust the network structure or target resolution.
