### ISSUE TITLE
Speeding up training/testing

### ISSUE THREAD

**Issue by loftusa** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#59]
Hi,

I have access to a big server with 6 GPUs and 64 CPU's. I'm using three of the GPUs in a docker container to run some images through this.

Currently my config train file looks like:

```
    "datasets": {
        "train": {
            "name": "FFHQ",
            "mode": "HR", // whether need LR img
            "dataroot": "dataset/ffhq_64_512",
            "datatype": "img", //lmdb or img, path of img files
            "l_resolution": 64, // low resolution need to super_resolution
            "r_resolution": 512, // high resolution
            "batch_size": 2,
            "num_workers": 16,
            "use_shuffle": true,
            "data_len": -1 // -1 represents all data used in train
        },
```
where `num_workers` was changed from 8 to 16 in the default settings. However, training doesn't seem to noticeably have sped up (it's still about a minute per 50 iterations).

When I try to raise the batch_size, I start getting out-of-memory errors.
Is there a good way to speed up training by using the power of this server?

Thanks!

**Comment by Janspiry** [comment]
During the training process, I feel that the main bottleneck is the number of parameters in the model. Maybe you can tweak the model structure and train with multiple GPUs.

**Comment by yenluu** [comment]
@loftusa Hi - Did you end up figuring out a good way to speed up training?
