### ISSUE TITLE
 prepare_data.py:85: local variable 'env' referenced before assignment

### ISSUE THREAD

**Issue by Stiv2804** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#6]
File "data/prepare_data.py", line 85, in prepare
UnboundLocalError: local variable 'env' referenced before assignment

probably making an "if lmdb_save" around the lines (85,86) ?

**Comment by Janspiry** [comment]
I understood your meaning, thanks!

**Comment by Stiv2804** [comment]
And is there a reason why deactivating lmdb is to write --lmdb behind it?

**Comment by Janspiry** [comment]
At first, I just saved file as .png format default, --lmdb is another choice. However, I used the lmdb for the dataset read default, and reversed its meaning for uniformity. I will change the appropriate semantics for selection.

**Comment by Stiv2804** [comment]
ok, thanks for the quick response!
