### ISSUE TITLE
Would you like to scale your model up ?

### ISSUE THREAD

**Issue by christophschuhmann** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#63]
Hi,
i am one of the chairmen and co-founders of LAION ( https://laion.ai ).
If you would like to scale your image super resolution model up, to train with multiple nodes of 8xA100s an drelease it a open source, we can provide you with that.

I would be happy to hear back from you. christoph.schuhmann@laion.ai

**Comment by Janspiry** [comment]
Thank you so much for your help!!! , but I don't have enough time at the moment and I'm afraid I won't be able to do this job well. Thanks again for your kindness!
