### ISSUE TITLE
How to use the network with higher resolution images as inputs?

### ISSUE THREAD

**Issue by dersugiritlioglu** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#64]
Hello! I would like to finetune the model or infer with inputs of varying sizes, up to 1000x1000 in dimensions. Has anyone tried something like this yet? What is the most logical approach to this? 
I thought of taking 64x64 batches from a single image but the results are not totally consistent for concatenation and even the inference takes too long to finish for all of the images batches.

**Comment by Janspiry** [comment]
For batches, you can infer to #19. And varying sizes is an interesting proposition and so far I haven't seen anyone try it
