### ISSUE TITLE
对代码的理解问题求助

### ISSUE THREAD

**Issue by LiErSan123** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#68]
你好，我刚刚涉及到基于DDPM的论文以及代码。在看你这份代码的时候，我发现自己看不明白model.py、diffusion.py、unet.py中许多方法的目的，其中的一些参数我也不知道具体是在做些什么，我确实太菜了。不知道你有注释详细一些的代码版本吗。如果有的话，可以给我一份吗。真的很感谢你。

**Comment by Janspiry** [comment]
抱歉，我没有详细的注释版本。我的学习历程供参考：
1. 知乎的简要介绍，https://zhuanlan.zhihu.com/p/366004028，https://zhuanlan.zhihu.com/p/384144179
2. 宋学长类似方法的讲解，https://www.techbeat.net/talk-info?id=509
3. lucidrains 的实现，https://github.com/lucidrains/denoising-diffusion-pytorch

SR3只是在DDPM步骤上加了个条件。

**Comment by LiErSan123** [comment]
好的，非常感谢，你的学习历程对我也有很大帮助。再次感谢，祝你在学业上步步高升！
