### ISSUE TITLE
Is it possible to upscale 512x512 to 1024x1024?

### ISSUE THREAD

**Issue by DanZinov** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#7]
I would like to upscale an image which is 512x512 to 1024x1024 or 2048x2048, is that possible with this model? Also will this work on natural images or just faces?

**Comment by Janspiry** [comment]
As described in the paper, it can suitable for natural images and high-resolution images. However, as far as my experiment is concerned, higher resolution requires larger model parameters, otherwise color distortion may occur.
