### ISSUE TITLE
Question about test set size

### ISSUE THREAD

**Issue by z562** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#70]
Question 1:
I find SR try to sample image one by one, and the test set size is set to 50. But there are 30,000 images in test set, Should I test SR3model on 30,000 test images?
Question 2:
If I set the test batch size to 50, the Metrics class do not work. How can I use large batch size to evaluation SR3 model?

**Comment by Janspiry** [comment]
1. Theoretically, you need to test all images, which wil takes a lot of time.
2. You need to first make inferences with the model, save the output, and then use the Metric class
