### ISSUE TITLE
inference a new test image is too slow？

### ISSUE THREAD

**Issue by tengshaofeng** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#74]
Thanks for your sharing. The result is amazing. But the inference time is too long? about 4 minitus for one image?

**Comment by 2714830587-xh** [comment]
maybe  ，its depend on your gpu!like me ,I have a 3060 gpu(6g),its inf time about 1min less

**Comment by Janspiry** [comment]
Feel free to reopen the issue if there is any question.

**Comment by huchi00057** [comment]
> 感謝您的分享。結果是驚人的。但是推理時間太長？一張圖片大約 4 分鐘？

In colab T4, it took 20min in a picture. more longer XDDD
