### ISSUE TITLE
Train a new model

### ISSUE THREAD

**Issue by yee-ran** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#75]
Hey, so I use custom datasets to train a new model. I had a problem here: [issue43](https://github.com/Janspiry/Image-Super-Resolution-via-Iterative-Refinement/issues/43)

Also I set json file as you did, total number iteration is 1000000. Currently I got:

22-08-13 22:22:32.332 - INFO: # Validation # PSNR: 5.4917e+00
22-08-13 22:22:32.332 - INFO: <epoch:110, iter:  50,000> psnr: 5.4917e+00

Is it normal not to see any improvements for now?

**Comment by Janspiry** [comment]
I think this is not normal. Could you put up the log and configuration?
