### ISSUE TITLE
What does l_pix mean?

### ISSUE THREAD

**Issue by superxianyuwang** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#81]
Thanks for your code.
I would like to ask what is the l_pix output on the terminal. Why does it fluctuate? Should it be a gradual decline?
Looking forward to your reply.

**Comment by ZhuoranT** [comment]
Thanks for Janspiry's code.
I also have the same question. The l_pix is fluctuating.
Looking forward to author's reply.

**Comment by uminaty** [comment]
Hy ! l_pix is the pixel wise loss. It is often a L1 or L2 loss (I think in the code it's a L1 loss by default).

It is completely normal for the loss to fluctuate and not just decrease. At each iteration the network takes in different images, the optimisation ensures that the network weights are modified as best as possible to minimise the error on the input images. At the next iteration, if the image is very different, the error will potentially be larger than the previous error. What matters is that, on average, the error decreases over the course of the training!

**Comment by superxianyuwang** [comment]
> Hy ! l_pix is the pixel wise loss. It is often a L1 or L2 loss (I think in the code it's a L1 loss by default).
> 
> It is completely normal for the loss to fluctuate and not just decrease. At each iteration the network takes in different images, the optimisation ensures that the network weights are modified as best as possible to minimise the error on the input images. At the next iteration, if the image is very different, the error will potentially be larger than the previous error. What matters is that, on average, the error decreases over the course of the training!

Thanks for your explanation.
