### ISSUE TITLE
About the training epoch

### ISSUE THREAD

**Issue by WangYibucea** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#84]
Thank you very much for the recurrence. But I only see n_iter in here, not how epoches are defined. If I missed it, could you please tell me. Thank you very much!

**Comment by AdamGradient** [comment]
don't you know  that epoch * sample_num = iter * batch ?

**Comment by huchi00057** [comment]
> don't you know that epoch * sample_num = iter * batch ?

Is samle_num equal to amount of train images?
I'm not sure what is sample_num

**Comment by huchi00057** [comment]
> Thank you very much for the recurrence. But I only see n_iter in here, not how epoches are defined. If I missed it, could you please tell me. Thank you very much!

In conclsion, how many epoch did it execute?

**Comment by Janspiry** [comment]
Sorry, I only counted iterations, and the relevant epoch can be calculated according to the above formula. Feel free to reopen the issue if there is any question.
