### ISSUE TITLE
Sampling throws the following error:

### ISSUE THREAD

**Issue by hizzlehoff** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#85]
Thank you for sharing the project.

I'm getting the following error, I thought it had to do with the pyTorch version but after trying the minimum in the requirements file I still get the error. I'm not that familiar with Torch and would appreciate some help:

> 22-11-07 19:04:58.564 - INFO: Model [DDPM] is created.
> 22-11-07 19:04:58.564 - INFO: Initial Model Finished
> 22-11-07 19:04:58.565 - INFO: Begin Model Inference.
> Traceback (most recent call last):
>   File "infer.py", line 70, in <module>
>     diffusion.test(continous=True)
>   File "/content/Image-Super-Resolution-via-Iterative-Refinement/model/model.py", line 68, in test
>     self.data['SR'], continous)
>   File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
>     return func(*args, **kwargs)
>   File "/content/Image-Super-Resolution-via-Iterative-Refinement/model/sr3_modules/diffusion.py", line 210, in super_resolution
>     return self.p_sample_loop(x_in, continous)
>   File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
>     return func(*args, **kwargs)
>   File "/content/Image-Super-Resolution-via-Iterative-Refinement/model/sr3_modules/diffusion.py", line 182, in p_sample_loop
>     img = torch.randn(shape, device=device)
> TypeError: randn() received an invalid combination of arguments - got (Tensor, device=torch.device), but expected one of:> 22-11-07 19:04:58.564 - INFO: Model [DDPM] is created.
> 22-11-07 19:04:58.564 - INFO: Initial Model Finished
> 22-11-07 19:04:58.565 - INFO: Begin Model Inference.
> Traceback (most recent call last):
>   File "infer.py", line 70, in <module>
>     diffusion.test(continous=True)
>   File "/content/Image-Super-Resolution-via-Iterative-Refinement/model/model.py", line 68, in test
>     self.data['SR'], continous)
>   File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
>     return func(*args, **kwargs)
>   File "/content/Image-Super-Resolution-via-Iterative-Refinement/model/sr3_modules/diffusion.py", line 210, in super_resolution
>     return self.p_sample_loop(x_in, continous)
>   File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
>     return func(*args, **kwargs)
>   File "/content/Image-Super-Resolution-via-Iterative-Refinement/model/sr3_modules/diffusion.py", line 182, in p_sample_loop
>     img = torch.randn(shape, device=device)
> TypeError: randn() received an invalid combination of arguments - got (Tensor, device=torch.device), but expected one of:
>  * (tuple of ints size, *, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
>  * (tuple of ints size, *, torch.Generator generator, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
>  * (tuple of ints size, *, torch.Generator generator, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
>  * (tuple of ints size, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
> 
> 
>  * (tuple of ints size, *, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
>  * (tuple of ints size, *, torch.Generator generator, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
>  * (tuple of ints size, *, torch.Generator generator, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
>  * (tuple of ints size, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
> 
>

**Comment by hizzlehoff** [comment]
I got it to run by changing on line 182 and line 191 of diffusion.py:
img = torch.randn(shape, device=device)

to 

img = torch.randn(shape.size(), device=device)

**Comment by hizzlehoff** [comment]
And for the DDPM diffusion.py:

change:

b = shape[0]

to:

tmpShape = shape.size()
b = tmpShape[0]


in both instance.s

**Comment by Janspiry** [comment]
Feel free to reopen the issue if there is any question.
