### ISSUE TITLE
why need to set the SR path during inference?

### ISSUE THREAD

**Issue by anguoyang** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#87]
https://github.com/Janspiry/Image-Super-Resolution-via-Iterative-Refinement/blob/master/data/LRHR_dataset.py#L29
When I run the infer or sr.py, I need to put SR images into folder like sr_64_512 beforehand, otherwise will generate error, if my understanding is correct, the SR image should be the result/output image right? thank you

**Comment by stu-GYULA** [comment]
The sr images are generated by oversampling lr images using bicubic in prepare_data.py.  Further, SR3 model oversample the generated sr images.

**Comment by Janspiry** [comment]
Thanks for the above correct and patient answers

**Comment by masuxin** [comment]
> 

I have the same doubt, if the SR images are required for the test, what is the output of the SR3? I originally thought its output was an SR images.
