### ISSUE TITLE
Inferencing instruction are cryptic.

### ISSUE THREAD

**Issue by hizzlehoff** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#89]
Thank for sharing this repo.

I do have an issue with some of the instructions being quite cryptic. I have a hard time with the following:

"Set the image path like steps in Own Data, then run the script:"

Can somebody elaborate how I can just upscale a single image or a folder using a checkpoint?

**Comment by Janspiry** [comment]
Sorry for this, Own Data is a section of ReADME, which should provide a detailed description
