### ISSUE TITLE
poor image quality for my own SR dataset from scratch?

### ISSUE THREAD

**Issue by codgodtao** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#95]
Training the model from scratch on my superresolution dataset, and the result becomes very bad, i have test for many  parameter setting
for unet, learning rate schedule, init_method etc, so how to train a good enough model for my own dataset? could you give me some advise for your experience? Thank you a lot

![312480_1_sr_process](https://user-images.githubusercontent.com/52556203/206838451-c76b93b8-6729-4cef-9558-af94408db41b.png)

**Comment by Janspiry** [comment]
Sorry for this, you can find some advice in closed issues.
