### ISSUE TITLE
size of input image

### ISSUE THREAD

**Issue by shenhaiyoualn** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#96]
I noticed that the size of the input image and the output image are both 2 to the nth power. If I want to input an image with an input size of 300, an error will be reported. How do I modify the code for this, thank you!
![qus](https://user-images.githubusercontent.com/52127848/207037480-2e56fe62-9f2d-44bd-b9ec-8b3f07da6fab.jpg)

**Comment by Janspiry** [comment]
The current code is not flexible enough to support various sizes, you can:
1. Modify the convolution of Unet to fit the new size
2. Crop the original image to the right size
