### ISSUE TITLE
测试波动，部分图片质量很差

### ISSUE THREAD

**Issue by wangzhen699** [Janspiry/Image-Super-Resolution-via-Iterative-Refinement#99]
您好，非常感谢您的工作，请问有没有遇到测试波动的问题？部分超分图片含有很多的噪声。

**Comment by Janspiry** [comment]
有的，需要进一步训练。
![image](https://user-images.githubusercontent.com/32922494/216626422-a914b626-b967-4765-98c1-09a97036c69f.png)
